services:
  api:
    image: muonsoft/openapi-mock
    ports:
      - "8080:8080"
    environment:
      - "OPENAPI_MOCK_SPECIFICATION_URL=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml"
  proxy:
    depends_on: 
      - api
    image: "tp3"
    ports:
      - "80:80"
